import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { notFound } from "next/navigation";
import { ContentPage, LegalPage, PageHero, Checklist } from "@/components/page-shell";
import { destinations } from "@/data/destinations";
import { services } from "@/data/services";
import { BreadcrumbSchema } from "@/components/seo/json-ld";
import { siteConfig } from "@/config/site";

const pages: Record<string, { title: string; eyebrow: string; description: string; sections: { title: string; text: string }[] }> = {
  about: { title: "Professional Guidance, Centred on You", eyebrow: "About Edriva Global", description: "Clear advice and practical support for students making important international education decisions.", sections: [{ title: "Who We Are", text: "Edriva Global is an international education consultancy supporting students as they research, prepare and apply for study opportunities abroad." }, { title: "Our Mission", text: "To make international education planning more transparent, organised and personal for every student we advise." }, { title: "Our Vision", text: "A world where students can pursue the right education opportunity with confidence and reliable guidance." }, { title: "Our Approach", text: "We start by listening, then build a practical plan around academic background, priorities, budget and long-term goals." }, { title: "Our Values", text: "Integrity, transparency, a student-first mindset, global perspective, professional excellence and long-term support guide our work." }] },
  universities: { title: "Universities Students Explore", eyebrow: "Academic possibilities", description: "Explore institutions and programs across leading international study destinations.", sections: [{ title: "Find the Right Academic Environment", text: "University selection is about more than rankings. We help students consider course content, location, entry criteria, budget and career relevance." }, { title: "Independent Guidance", text: "Universities shown on this website are examples for exploration and do not imply an official partnership unless explicitly stated." }] },
  scholarships: { title: "Make Global Education More Affordable", eyebrow: "Scholarship guidance", description: "Explore funding routes and prepare thoughtful, well-organised scholarship applications.", sections: [{ title: "Funding Opportunities", text: "Students may explore merit-based awards, government funding, university scholarships, tuition fee waivers and country-specific schemes." }, { title: "How We Help", text: "We help you identify relevant options, understand published criteria and organise supporting documents. Funding decisions remain with each scholarship provider." }] },
  "student-journey": { title: "Your Journey, Clearly Planned", eyebrow: "From ambition to arrival", description: "A structured path through research, applications, offers, visa preparation and pre-departure planning.", sections: [{ title: "Discover", text: "Clarify your goals and identify realistic countries, universities and programs." }, { title: "Prepare", text: "Build a timeline and organise academic, financial and supporting documents." }, { title: "Apply", text: "Submit carefully reviewed applications and keep track of decisions and next steps." }, { title: "Get Ready", text: "Prepare visa documentation, accommodation research and practical plans for arrival." }] },
  contact: { title: "Let’s Talk About Your Study Plans", eyebrow: "Contact Edriva Global", description: "Share where you are now and where you hope to study. We’ll help you identify a sensible next step.", sections: [{ title: "Email Our Team", text: "General enquiries: info@edrivaglobal.com. Admissions enquiries: admissions@edrivaglobal.com." }, { title: "Business Details", text: "Phone, WhatsApp and office address are awaiting confirmation in the central site configuration." }] },
  services: { title: "Support for Every Stage", eyebrow: "Our services", description: "Professional guidance from your first shortlist through application and pre-departure planning.", sections: services.map((item) => ({ title: item.title, text: item.description })) },
  destinations: { title: "Explore Study Destinations", eyebrow: "Global opportunities", description: "Compare academic environments, cities and study options across eight leading destinations.", sections: destinations.map((item) => ({ title: item.name, text: item.description })) },
};

const legal = ["privacy-policy", "terms", "disclaimer"];
export function generateStaticParams() { return [...Object.keys(pages), ...legal].map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const page = pages[slug]; const title = page?.title ?? (slug === "privacy-policy" ? "Privacy Policy" : slug === "terms" ? "Terms & Conditions" : "Website Disclaimer"); const description = page?.description ?? `Read the Edriva Global ${title.toLowerCase()} and important website information.`; return { title, description, alternates: { canonical: `/${slug}` }, openGraph: { title, description, url: `/${slug}`, type: "website" }, twitter: { card: "summary_large_image", title, description } }; }

export default async function TopLevelPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const breadcrumb = <BreadcrumbSchema items={[{ name: "Home", url: siteConfig.domain }, { name: pages[slug]?.title ?? slug.replaceAll("-", " "), url: `${siteConfig.domain}/${slug}` }]} />;
  if (legal.includes(slug)) return <>{breadcrumb}<LegalPage title={slug === "privacy-policy" ? "Privacy Policy" : slug === "terms" ? "Terms & Conditions" : "Disclaimer"}><h2>Overview</h2><p>This page contains placeholder legal content and must be reviewed by a qualified professional before publication.</p><h2>Information we provide</h2><p>Education, admissions, scholarship and visa information can change. Students should verify current details with official universities, scholarship providers and government authorities.</p><h2>Contact</h2><p>Questions may be sent to info@edrivaglobal.com.</p></LegalPage></>;
  const page = pages[slug]; if (!page) notFound();
  if (slug === "destinations") return <>{breadcrumb}<PageHero eyebrow={page.eyebrow} title={page.title} description={page.description} /><section className="section container destination-grid listing-grid">{destinations.map((item) => <article className="destination-card" key={item.slug}><Link href={`/destinations/${item.slug}`} className="destination-image"><Image src={item.image} alt={item.name} fill sizes="(max-width: 700px) 100vw, 33vw" /></Link><div className="destination-content"><span className="flag-code">{item.flag}</span><h2>{item.name}</h2><p>{item.description}</p><Link href={`/destinations/${item.slug}`}>Explore Country <ArrowRight /></Link></div></article>)}</section></>;
  if (slug === "about") return <>{breadcrumb}<ContentPage {...page} /><section className="values-band"><div className="container"><h2>What Guides Our Work</h2><Checklist items={["Integrity", "Transparency", "Student First", "Global Perspective", "Professional Excellence", "Long-Term Support"]} /></div></section></>;
  return <>{breadcrumb}<ContentPage {...page} /></>;
}
